using System.Linq;
using Content.Shared._ForkStation.PersistentPrisoner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ForkStation.PersistentPrisoner;

[GenerateTypedNameReferences]
public sealed partial class PenaltyConsoleWindow : DefaultWindow
{
    public event Action<string>? OnPlayerSelected;
    public event Action<string, int, string>? OnAddPenalty;
    public event Action<int>? OnUndoPenalty;

    private string? _selectedPlayer;
    private PenaltyConsoleState? _lastState;
    private int _selectedPenaltyId = -1;

    public PenaltyConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        PlayerList.OnItemSelected += OnPlayerItemSelected;
        SearchBar.OnTextChanged += OnSearchChanged;
        AddPenaltyButton.OnPressed += _ => ShowAddPanel();
        CancelPenaltyButton.OnPressed += _ => HideAddPanel();
        ConfirmPenaltyButton.OnPressed += _ => ConfirmPenalty();
        UndoPenaltyButton.OnPressed += _ => UndoSelected();
        PenaltyList.OnItemSelected += OnPenaltyItemSelected;

        // Initialize spinbox range
        RoundsSpinBox.Value = 1;
    }

    private void OnPlayerItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemIndex < 0 || args.ItemIndex >= PlayerList.Count)
            return;

        var item = PlayerList[args.ItemIndex];
        if (item.Metadata is string playerName)
        {
            _selectedPlayer = playerName;
            OnPlayerSelected?.Invoke(playerName);
        }
    }

    private void OnPenaltyItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemIndex < 0 || args.ItemIndex >= PenaltyList.Count)
            return;

        var item = PenaltyList[args.ItemIndex];
        if (item.Metadata is int penaltyId)
        {
            _selectedPenaltyId = penaltyId;
            UndoPenaltyButton.Disabled = false;
        }
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        if (_lastState != null)
            PopulatePlayerList(_lastState);
    }

    private void ShowAddPanel()
    {
        AddPenaltyPanel.Visible = true;
        ReasonEdit.Text = "";
        RoundsSpinBox.Value = 1;
    }

    private void HideAddPanel()
    {
        AddPenaltyPanel.Visible = false;
    }

    private void ConfirmPenalty()
    {
        if (_selectedPlayer == null)
            return;

        var rounds = RoundsSpinBox.Value;
        if (rounds < 1) rounds = 1;
        if (rounds > 5) rounds = 5;

        var reason = ReasonEdit.Text?.Trim();
        if (string.IsNullOrWhiteSpace(reason))
            return;

        OnAddPenalty?.Invoke(_selectedPlayer, rounds, reason);
        HideAddPanel();
    }

    private void UndoSelected()
    {
        if (_selectedPenaltyId >= 0)
        {
            OnUndoPenalty?.Invoke(_selectedPenaltyId);
            _selectedPenaltyId = -1;
            UndoPenaltyButton.Disabled = true;
        }
    }

    public void UpdateState(PenaltyConsoleState state)
    {
        _lastState = state;
        PopulatePlayerList(state);
        UpdateSelectedPlayer(state);
    }

    private void PopulatePlayerList(PenaltyConsoleState state)
    {
        PlayerList.Clear();
        var search = SearchBar.Text?.Trim().ToLowerInvariant() ?? "";

        var sorted = state.Players
            .OrderByDescending(p => p.Value.TotalPenalties)
            .ThenBy(p => p.Key);

        foreach (var (name, entry) in sorted)
        {
            if (!string.IsNullOrEmpty(search) && !name.ToLowerInvariant().Contains(search))
                continue;

            var prefix = "";
            if (entry.TotalPenalties >= 15)
                prefix = "[!!!] ";
            else if (entry.TotalPenalties >= 10)
                prefix = "[!!] ";
            else if (entry.TotalPenalties > 0)
                prefix = "[!] ";

            var penaltyText = entry.TotalPenalties > 0 ? $" [{entry.TotalPenalties}r]" : "";
            var display = $"{prefix}{name} ({entry.JobTitle}){penaltyText}";

            var item = PlayerList.AddItem(display);
            item.Metadata = name;
        }
    }

    private void UpdateSelectedPlayer(PenaltyConsoleState state)
    {
        _selectedPlayer = state.SelectedPlayer;
        PenaltyList.Clear();
        _selectedPenaltyId = -1;
        UndoPenaltyButton.Disabled = true;

        if (state.SelectedPlayer == null || !state.Players.TryGetValue(state.SelectedPlayer, out var entry))
        {
            SelectedNameLabel.Text = "No player selected";
            SelectedJobLabel.Text = "";
            PenaltyCountLabel.Text = "";
            DangerLabel.Text = "";
            AddPenaltyButton.Disabled = true;
            return;
        }

        SelectedNameLabel.Text = state.SelectedPlayer;
        SelectedJobLabel.Text = entry.JobTitle;
        AddPenaltyButton.Disabled = false;

        if (entry.TotalPenalties > 0)
        {
            PenaltyCountLabel.Text = $"Penalty Rounds: {entry.TotalPenalties}";

            if (entry.TotalPenalties >= 15)
                DangerLabel.Text = "EXTREMELY DANGEROUS - SOLITARY CONFINEMENT";
            else if (entry.TotalPenalties >= 10)
                DangerLabel.Text = "DANGEROUS";
            else
                DangerLabel.Text = "";
        }
        else
        {
            PenaltyCountLabel.Text = "No active penalties";
            DangerLabel.Text = "";
        }

        // Populate penalty list
        if (state.SelectedPenalties != null)
        {
            foreach (var p in state.SelectedPenalties.OrderByDescending(x => x.IssuedAt))
            {
                var status = p.RoundsRemaining > 0 ? $"{p.RoundsRemaining}r remaining" : "SERVED";
                var source = p.AdminIssued ? "ADMIN" : "SEC";
                var display = $"#{p.Id} [{status}] {p.RoundsAssigned}r by {p.IssuedByName} ({source}) - {p.Reason}";

                var item = PenaltyList.AddItem(display);
                item.Metadata = p.Id;

                // Served penalties show differently in text already via [SERVED] prefix
            }
        }
    }
}
