<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AssemblyName>Mafiastation.AiPilotLab</AssemblyName>
    <RootNamespace>Mafiastation.AiPilotLab</RootNamespace>
  </PropertyGroup>
</Project>
